use std::collections::HashSet;

use askama::Template;
use askama_axum::IntoResponse;
use axum::extract::{Path, Query, State};
use axum::http::{header, HeaderMap, HeaderValue};
use axum::response::{Redirect, Response};
use axum::routing::{get, post};
use axum::{Form, Router};
use futures_util::future::join_all;
use serde::Deserialize;
use tower_sessions::Session;

use crate::audit;
use crate::auth;
use crate::cache::{self, SearchCache};
use crate::i18n;
use crate::sources::health;
use crate::sources::{
    Difficulty, Instrument, ScoreType, SearchFilters, SearchResult, Source,
};
use std::sync::Arc;

use super::AppState;

const MAX_PDF_BYTES: usize = 10 * 1024 * 1024;
/// How many results to ask each upstream source for, on page 1. Set to 20
/// to match MuseScore's natural search-page size (their /sheetmusic page
/// always renders 20 cards, capped by our scraper's `.take(limit)` — so
/// limit=10 was discarding half the cards we'd already fetched for free).
/// IMSLP's OpenSearch and Mutopia's CGI both handle limit=20 with no extra
/// upstream cost (single HTTP call, larger response slice). Page N then
/// fans out to `SEARCH_LIMIT_PER_SOURCE * N` per source, matching the
/// cumulative target_count.
const SEARCH_LIMIT_PER_SOURCE: usize = 20;
/// Target page size for the unified, post-dedup result list. Each page N
/// shows results 1..(N * SEARCH_PAGE_SIZE) (the simple full-replace
/// pagination flow — see `search_results.html`). 20 keeps the badge-laden
/// cards from overflowing the viewport on first paint while still showing
/// noticeably more than a single source's worth.
const SEARCH_PAGE_SIZE: usize = 20;
/// Hard upper bound on `?page=N`. Bounds both upstream per-source `limit`
/// and the post-dedup slice; without it a malicious request could ask for
/// page=10000 and we'd happily fan out limit=100000 per source.
const SEARCH_MAX_PAGE: u32 = 10;

/// Tailwind-compiled stylesheet. Generated by the Docker builder (or by
/// build.rs as an empty stub for local cargo check). Served by `/static/app.css`.
const APP_CSS: &str = include_str!("../../dist/styles.css");
/// Typeahead: ignore queries shorter than this. Avoids 1-char query storms
/// while users are still typing the start of a name.
const SEARCH_MIN_QUERY_LEN: usize = 2;

#[derive(Template)]
#[template(path = "search.html")]
struct SearchPage {
    query: String,
    results: Vec<SearchResult>,
    message: Option<String>,
    /// `Some(n)` when there is likely more to fetch — the trimmed result
    /// list filled the requested page exactly. `None` once we know we've
    /// hit the end (or pagination is otherwise unavailable, e.g. empty
    /// query). The template renders an HTMX "Load more" button only when
    /// `Some`. `SearchPage` and `ResultsPartial` share the partial via
    /// `{% include %}`, so their context shapes must match.
    next_page: Option<u32>,
    sources: Vec<SourceFilterOption>,
    instruments: Vec<FilterOption>,
    difficulties: Vec<FilterOption>,
    score_types: Vec<FilterOption>,
    /// Current state of the public-domain-only toggle. Distinct from the
    /// dropdowns because there's no list of options — it's a single
    /// checkbox chip.
    public_domain_only: bool,
    /// How many source checkboxes are currently ticked. Drives the count
    /// badge next to "Sources ▾" in the filter dropdown ("Sources [2]"
    /// when not all are selected). Live-updated by a small JS in
    /// search.html on checkbox change since the HTMX swap only updates
    /// `#results`, not the filter UI.
    selected_source_count: usize,
    /// True iff any filter is set to a non-default value (any dropdown
    /// non-default, any source unticked, or PD-only on). Drives the
    /// visibility of the "Reset filters" link.
    has_active_filters: bool,
    /// `Some(url)` when this render should embed the deferred MuseScore
    /// loader (`<div hx-get=…>`) — i.e. the first page of a real query
    /// with MuseScore among the selected sources. The URL hits
    /// `/search?defer=musescore&…`. `None` suppresses the loader (home
    /// page, MuseScore unticked, append/defer responses). See
    /// `build_musescore_defer_url`.
    musescore_defer_url: Option<String>,
    /// True exactly when `musescore_defer_url` is `Some` — MuseScore is
    /// still streaming in below. Suppresses the "End of results" divider
    /// in the shared items partial so it doesn't render above the pending
    /// MuseScore block. Kept as a separate flag because the items partial
    /// can't `match` the Option in a boolean context.
    musescore_pending: bool,
}

#[derive(Template)]
#[template(path = "search_results.html")]
struct ResultsPartial {
    query: String,
    results: Vec<SearchResult>,
    next_page: Option<u32>,
    musescore_defer_url: Option<String>,
    musescore_pending: bool,
}

/// Deferred MuseScore block, returned by `/search?defer=musescore&…`.
/// Rendered into the `#musescore-deferred` loader once the fast sources
/// have painted. Shares `_result_card.html` with the unified list.
#[derive(Template)]
#[template(path = "search_musescore.html")]
struct MusescorePartial {
    results: Vec<SearchResult>,
}

/// Infinite-scroll append response. Same shape as `ResultsPartial` — both
/// templates render `_search_results_items.html` — but `append`'s wrapper
/// drops the `<ul>` because the new items get spliced into the existing
/// list via `hx-swap="outerHTML"` on the previous sentinel.
#[derive(Template)]
#[template(path = "search_results_append.html")]
struct ResultsAppendPartial {
    query: String,
    results: Vec<SearchResult>,
    next_page: Option<u32>,
    /// Always false on the append path — MuseScore is loaded once on
    /// page 1, never during infinite-scroll. Present only because the
    /// shared `_search_results_items.html` references it.
    musescore_pending: bool,
}

struct SourceFilterOption {
    id: &'static str,
    display: &'static str,
    selected: bool,
}

/// Generic slug/display/selected triple used by every single-select filter
/// dropdown (instrument, difficulty, score type). Same shape; the
/// template just iterates and renders.
struct FilterOption {
    slug: &'static str,
    display: &'static str,
    selected: bool,
}

/// Aggregate of every filter-control's UI state. Bundled into one struct
/// rather than threaded through `build_filter_options`'s return tuple
/// because adding a new filter would otherwise touch every call site.
struct FilterUiState {
    sources: Vec<SourceFilterOption>,
    instruments: Vec<FilterOption>,
    difficulties: Vec<FilterOption>,
    score_types: Vec<FilterOption>,
}

/// Build the per-render filter UI state.
///
/// `source_filter = None` means "no `sources` param present in the URL" — the
/// default, all checkboxes ticked. `Some(set)` means the user supplied a
/// specific subset (possibly empty); we honour exactly that.
fn build_filter_options(
    state: &AppState,
    source_filter: Option<&HashSet<String>>,
    filters: &SearchFilters,
) -> FilterUiState {
    let sources = state
        .sources
        .iter()
        .map(|s| SourceFilterOption {
            id: s.id(),
            display: s.display_name(),
            selected: source_filter
                .map(|f| f.contains(s.id()))
                .unwrap_or(true),
        })
        .collect();
    let instruments = Instrument::ALL
        .iter()
        .map(|i| FilterOption {
            slug: i.slug(),
            display: i.display(),
            selected: filters.instrument == Some(*i),
        })
        .collect();
    let difficulties = Difficulty::ALL
        .iter()
        .map(|d| FilterOption {
            slug: d.slug(),
            display: d.display(),
            selected: filters.difficulty == Some(*d),
        })
        .collect();
    let score_types = ScoreType::ALL
        .iter()
        .map(|t| FilterOption {
            slug: t.slug(),
            display: t.display(),
            selected: filters.score_type == Some(*t),
        })
        .collect();
    FilterUiState {
        sources,
        instruments,
        difficulties,
        score_types,
    }
}

/// Post-hoc filter: drop results that don't match the difficulty / PD-only
/// / score-type filters. `instrument` filtering already happened upstream
/// (push-down to each source), so we don't re-check it here.
///
/// Conservatism on missing data:
///   - `public_domain_only`: a `None` is_public_domain means "unknown"
///     (MuseScore DOM-scrape fallback). Drop those when the filter is on
///     — the user explicitly asked for known-PD only.
///   - `difficulty`: IMSLP/Mutopia have complexity=None. Drop them when a
///     specific difficulty is selected; surfacing them would mean "show
///     me beginner pieces" returns non-beginner content silently.
///   - `score_type = Community`: keep is_official=Some(false) AND
///     is_official=None (IMSLP/Mutopia are inherently community).
///   - `score_type = Official`: only keep is_official=Some(true).
fn passes_post_hoc(r: &SearchResult, filters: &SearchFilters) -> bool {
    if filters.public_domain_only && r.is_public_domain != Some(true) {
        return false;
    }
    if let Some(d) = filters.difficulty {
        if r.complexity.and_then(Difficulty::from_complexity) != Some(d) {
            return false;
        }
    }
    if let Some(st) = filters.score_type {
        match st {
            ScoreType::Official => {
                if r.is_official != Some(true) {
                    return false;
                }
            }
            ScoreType::Community => {
                if r.is_official == Some(true) {
                    return false;
                }
            }
        }
    }
    true
}

/// Parse the `sources` query param(s). Returns `None` when no `sources` key
/// is present at all (default = all enabled). Accepts both repeated
/// (`?sources=a&sources=b`) and comma-separated (`?sources=a,b`) forms so
/// hand-typed URLs stay friendly while HTMX form serialization works
/// out-of-the-box.
fn parse_source_filter(params: &[(String, String)]) -> Option<HashSet<String>> {
    let mut acc = HashSet::new();
    let mut saw_any = false;
    for (k, v) in params {
        if k != "sources" {
            continue;
        }
        saw_any = true;
        for part in v.split(',') {
            let trimmed = part.trim();
            if !trimmed.is_empty() {
                acc.insert(trimmed.to_string());
            }
        }
    }
    if saw_any {
        Some(acc)
    } else {
        None
    }
}

fn first_param<'a>(params: &'a [(String, String)], key: &str) -> Option<&'a str> {
    params
        .iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v.as_str())
}

#[derive(Template)]
#[template(path = "login.html")]
struct LoginTemplate {
    error: Option<String>,
}

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/", get(home))
        .route("/healthz", get(healthz))
        .route("/static/app.css", get(app_css))
        .route("/search", get(search))
        .route("/pdf/:source_id/:id", get(pdf_handler))
        .route("/thumbnail/:source_id/:id", get(thumbnail_handler))
        .route("/login", get(login_page).post(login_submit))
        .route("/logout", post(logout))
}

/// Lazy thumbnail resolver. Two flavours of source, tried in order:
///   1. `Source::thumbnail_url` returns a CDN URL (e.g., IMSLP scraped
///      from the wiki page) → we redirect, caching the URL string in
///      `state.thumbnail_cache` for 24h.
///   2. `Source::thumbnail_bytes` returns inline PNG bytes (e.g.,
///      Mutopia rasterizes the PDF's first page via pdftoppm) → we
///      serve the bytes with a long Cache-Control so the browser cache
///      absorbs repeat loads, and stash them in
///      `state.thumbnail_bytes_cache` so refreshes within the TTL skip
///      the fetch + rasterize entirely.
/// Both Err → 404; the template's `onerror` handler hides the broken
/// image and falls back to the generic placeholder.
async fn thumbnail_handler(
    State(state): State<AppState>,
    Path((source_id, id)): Path<(String, String)>,
) -> Response {
    let key = format!("{source_id}:{id}");

    if let Some(url) = state.thumbnail_cache.get(&key).await {
        return Redirect::temporary(&url).into_response();
    }
    if let Some(entry) = state.thumbnail_bytes_cache.get(&key).await {
        return inline_thumbnail(&entry.0, entry.1);
    }

    let source = match state.find_source(&source_id) {
        Some(s) => s,
        None => {
            return (axum::http::StatusCode::NOT_FOUND, "unknown source").into_response();
        }
    };

    // Prefer the URL-based path: it's cheap (one HTTP HEAD-equivalent
    // scrape) and lets the CDN absorb load. Fall through to inline
    // bytes only if the source can't produce a URL.
    match source.thumbnail_url(&id).await {
        Ok(url) => {
            state.thumbnail_cache.insert(key, url.clone()).await;
            return Redirect::temporary(&url).into_response();
        }
        Err(url_err) => match source.thumbnail_bytes(&id).await {
            Ok((bytes, mime)) => {
                let resp = inline_thumbnail(&bytes, mime);
                state
                    .thumbnail_bytes_cache
                    .insert(key, Arc::new((bytes, mime)))
                    .await;
                resp
            }
            Err(bytes_err) => {
                tracing::warn!(
                    url_error = %url_err,
                    bytes_error = %bytes_err,
                    source = %source_id,
                    id = %id,
                    "thumbnail fetch failed"
                );
                (axum::http::StatusCode::NOT_FOUND, "no thumbnail").into_response()
            }
        },
    }
}

/// Serve thumbnail bytes inline with a long browser-cache TTL. Same
/// 24h window as the server-side moka cache; the URL itself is keyed
/// on a stable (source, id) pair so cache invalidation isn't a concern.
fn inline_thumbnail(bytes: &[u8], mime: &'static str) -> Response {
    let mut headers = HeaderMap::new();
    headers.insert(header::CONTENT_TYPE, HeaderValue::from_static(mime));
    headers.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=86400"),
    );
    (headers, bytes.to_vec()).into_response()
}

async fn app_css() -> Response {
    let mut headers = HeaderMap::new();
    headers.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("text/css; charset=utf-8"),
    );
    // Short TTL: the URL is not content-hashed so a long cache would
    // make deploys invisible. 60s matches the search-results cache.
    headers.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=60"),
    );
    (headers, APP_CSS).into_response()
}

async fn home(State(state): State<AppState>) -> impl IntoResponse {
    let ui = build_filter_options(&state, None, &SearchFilters::default());
    // Home page: no filters set, every source ticked.
    let selected_source_count = ui.sources.len();
    SearchPage {
        query: String::new(),
        results: Vec::new(),
        message: None,
        next_page: None,
        selected_source_count,
        has_active_filters: false,
        public_domain_only: false,
        sources: ui.sources,
        instruments: ui.instruments,
        difficulties: ui.difficulties,
        score_types: ui.score_types,
        musescore_defer_url: None,
        musescore_pending: false,
    }
}

async fn healthz() -> &'static str {
    "ok"
}

async fn search(
    State(state): State<AppState>,
    headers: HeaderMap,
    // Vec<(String, String)> preserves repeated query keys (HTMX serialises
    // the `sources` checkbox group as `?sources=imslp&sources=mutopia`),
    // which a HashMap would clobber. Single-value params (`q`, `instrument`)
    // are read out via first_param().
    Query(params): Query<Vec<(String, String)>>,
) -> Response {
    let query = first_param(&params, "q")
        .unwrap_or_default()
        .trim()
        .to_string();
    let instrument = first_param(&params, "instrument")
        .filter(|s| !s.is_empty())
        .and_then(Instrument::from_slug);
    let difficulty = first_param(&params, "difficulty")
        .filter(|s| !s.is_empty())
        .and_then(Difficulty::from_slug);
    let score_type = first_param(&params, "score_type")
        .filter(|s| !s.is_empty())
        .and_then(ScoreType::from_slug);
    // Toggle param accepts "1" or "true" as truthy; anything else is off.
    let public_domain_only = first_param(&params, "pd_only")
        .is_some_and(|s| s == "1" || s.eq_ignore_ascii_case("true"));
    let source_filter = parse_source_filter(&params);
    let filters = SearchFilters {
        instrument,
        difficulty,
        public_domain_only,
        score_type,
    };

    let is_htmx = headers.get("hx-request").is_some();
    let ip = audit::client_ip(&headers);
    let ua = audit::user_agent(&headers);

    // 1-based page index. Out-of-range / unparsable / over-cap inputs fall
    // back to page 1; we'd rather show something than 4xx the user.
    let page: u32 = first_param(&params, "page")
        .and_then(|s| s.parse::<u32>().ok())
        .filter(|p| *p >= 1 && *p <= SEARCH_MAX_PAGE)
        .unwrap_or(1);

    // Infinite-scroll append mode: triggered by the sentinel `<li>` at the
    // bottom of the current results list. Returns just *this* page's new
    // items (sliced from the cumulative dedup) wrapped in a bare partial
    // that gets spliced into the existing list via hx-swap="outerHTML".
    // Gated on the HTMX request header so hand-typed `?append=1` URLs
    // gracefully render the full page instead of a bare fragment.
    let is_append =
        is_htmx && first_param(&params, "append").is_some_and(|s| !s.is_empty());
    // Deferred MuseScore fan-out: the second request fired by the
    // `#musescore-deferred` loader once the fast sources have painted.
    // Queries MuseScore *only* and returns a bare card block. Gated on the
    // HTMX header so a hand-typed `?defer=musescore` URL falls through to a
    // normal full search (which includes MuseScore inline) rather than
    // rendering an orphan fragment.
    let is_defer =
        is_htmx && first_param(&params, "defer") == Some("musescore");

    if query.is_empty() {
        audit::record(
            &state.pool,
            &ip,
            ua.as_deref(),
            "search",
            None,
            "empty_query",
            None,
        )
        .await;
        if is_defer {
            return MusescorePartial { results: Vec::new() }.into_response();
        }
        if is_append {
            return empty_append(&query);
        }
        return render_response(
            is_htmx,
            &state,
            &query,
            Vec::new(),
            None,
            source_filter.as_ref(),
            &filters,
            None,
        );
    }
    if query.chars().count() < SEARCH_MIN_QUERY_LEN {
        // Typeahead: too short to be useful and the upstream sources will
        // mostly return noise. Return an empty result set silently — the
        // user will keep typing.
        if is_defer {
            return MusescorePartial { results: Vec::new() }.into_response();
        }
        if is_append {
            return empty_append(&query);
        }
        return render_response(
            is_htmx,
            &state,
            &query,
            Vec::new(),
            None,
            source_filter.as_ref(),
            &filters,
            None,
        );
    }

    // Multilingual expansion: a single user query becomes up to 4 query
    // variants (English / Simplified / Traditional / Pinyin) when known
    // composer or instrument names are recognised. See src/i18n/alias.rs.
    let variants = i18n::expand_query(&query);

    // Source-selection narrows the fan-out at the route layer — disabled
    // sources never get a request fired, so it stays cheap. Default
    // (`source_filter = None`) means all sources are enabled.
    let selected_sources: Vec<Arc<dyn Source>> = state
        .sources
        .iter()
        .filter(|s| {
            source_filter
                .as_ref()
                .map(|f| f.contains(s.id()))
                .unwrap_or(true)
        })
        .cloned()
        .collect();

    // Whether MuseScore is in play for this query at all. Drives both the
    // deferred-loader emission (normal path) and the defer-mode fan-out.
    let musescore_selected = selected_sources.iter().any(|s| s.id() == "musescore");

    // Split the fan-out. MuseScore is the slow source (FlareSolverr) and is
    // loaded out-of-band via `?defer=musescore`, so the normal (fast) path
    // queries everything *except* MuseScore, and the defer path queries
    // *only* MuseScore. This is what keeps MuseScore from being the
    // limiting factor on first paint.
    let active_sources: Vec<Arc<dyn Source>> = selected_sources
        .iter()
        .filter(|s| (s.id() == "musescore") == is_defer)
        .cloned()
        .collect();

    // Cross-product: (source, variant) -> one parallel search future.
    // Failing futures get a logged warn + empty Vec; nothing poisons the
    // whole search.
    //
    // Exception: MuseScore only gets the user's original query, never
    // the CJK variant expansions. Reasoning:
    //   - MuseScore.com sits behind Cloudflare; we go through
    //     FlareSolverr, where each call spins up (or queues against)
    //     a headless Chromium that takes ~5–30 s.
    //   - 4 variants × MuseScore = 4 parallel FS calls per query,
    //     which routinely overflows FS's internal queue (depths of
    //     8–12) and trips timeouts.
    //   - MuseScore's catalog is overwhelmingly English-titled
    //     community uploads — the CJK variants find very few extra
    //     hits there relative to the load they generate. IMSLP and
    //     Mutopia (cheap HTTP fetches, multilingual catalogs) keep
    //     the full variant fan-out.
    let original_query = query.clone();
    let pairs: Vec<(Arc<dyn Source>, String)> = active_sources
        .iter()
        .flat_map(|s| {
            let src = s.clone();
            if src.id() == "musescore" {
                vec![(src, original_query.clone())]
            } else {
                variants
                    .iter()
                    .map(|v| (src.clone(), v.clone()))
                    .collect::<Vec<_>>()
            }
        })
        .collect();
    let search_cache: SearchCache = state.search_cache.clone();
    let health_map = state.source_health.clone();
    // Bump the per-source limit linearly with page number. The cache key in
    // src/cache.rs now includes `limit`, so each page's fetch caches under
    // its own slot — page 1's 10-per-source vec doesn't shadow page 2's
    // 20-per-source vec.
    let per_source_limit = SEARCH_LIMIT_PER_SOURCE * (page as usize);
    let futures = pairs.into_iter().map(|(src, v)| {
        let cache = search_cache.clone();
        let health = health_map.clone();
        let f = filters.clone();
        async move {
            match cache::cached_search(&cache, &src, &v, &f, per_source_limit).await {
                Ok(rs) => {
                    // Cache hits also count as "ok" — if the cache has a
                    // valid entry, the source was reachable within the last
                    // TTL (60s), which is good enough for liveness.
                    health::record_ok(&health, src.id());
                    rs
                }
                Err(e) => {
                    // `{:#}` flattens an anyhow chain into a single
                    // colon-separated line, which keeps the structured
                    // log readable while still surfacing the underlying
                    // cause ("flaresolverr search …: flaresolverr
                    // returned status=error message=…: …" instead of
                    // just "flaresolverr search …").
                    let chain = format!("{:#}", e);
                    tracing::warn!(
                        source = src.id(),
                        variant = %v,
                        error = %chain,
                        "source search failed"
                    );
                    health::record_err(&health, src.id(), &chain);
                    Vec::new()
                }
            }
        }
    });
    let groups = join_all(futures).await;

    // Dedupe across (source, id) — the same work commonly surfaces via
    // multiple variants (e.g. "Chopin" and "肖邦" both return it).
    let mut seen = HashSet::new();
    let mut results = Vec::new();
    for group in groups {
        for r in group {
            if seen.insert((r.source.clone(), r.id.clone())) {
                results.push(r);
            }
        }
    }
    let deduped_total = results.len();

    // Post-hoc filters (difficulty / pd_only / score_type). Applied
    // *before* the page-target truncate so pagination semantics stay
    // sane: page 1 of "Beginner only" returns the first 20 Beginner
    // results, not "the 20 results that happened to land in page 1
    // before filtering took out 18 of them". `instrument` was already
    // applied upstream at the source layer.
    results.retain(|r| passes_post_hoc(r, &filters));

    // Deferred MuseScore block returns here: just the first page-size
    // worth of MuseScore cards, no pagination and no audit row (the fast
    // search already logged this query, so logging again would double-count
    // in /admin/search_log). Per-source liveness was already recorded in
    // the fan-out closure above.
    if is_defer {
        results.truncate(SEARCH_PAGE_SIZE);
        return MusescorePartial { results }.into_response();
    }

    // Page-1 shows the first SEARCH_PAGE_SIZE; page-N shows the first
    // N * SEARCH_PAGE_SIZE. We always serve the cumulative slice (the
    // "Load more" button replaces the whole `#results` div), which keeps
    // back/forward navigation and full-page reloads of `?page=N` honest.
    let target_count = (page as usize).saturating_mul(SEARCH_PAGE_SIZE);
    if results.len() > target_count {
        results.truncate(target_count);
    }

    // Surface "Load more" only when we filled the requested page exactly
    // *and* we haven't yet hit the safety cap. If dedup left us short the
    // upstream sources have plausibly run out of new (source,id) hits;
    // exposing the button would just produce an empty next page.
    let next_page = if results.len() >= target_count && page < SEARCH_MAX_PAGE {
        Some(page + 1)
    } else {
        None
    };

    audit::record(
        &state.pool,
        &ip,
        ua.as_deref(),
        "search",
        Some(&query),
        "ok",
        Some(&format!(
            r#"{{"results":{},"variants":{},"page":{},"deduped":{}}}"#,
            results.len(),
            variants.len(),
            page,
            deduped_total,
        )),
    )
    .await;

    // No Cache-Control header on /search responses. The same URL serves
    // two different shapes (HTMX partial vs full page on native nav) and
    // browsers cache by URL only, so caching causes a partial to be
    // rendered as a full document after pressing Enter. The server-side
    // moka cache (`src/cache.rs`) already absorbs cross-user repeat
    // queries; the browser-side cache would only deduplicate same-user
    // self-repeat which isn't worth the partial-vs-full collision.
    if is_append {
        // Split off just this page's new items. The first
        // `(page-1)*PAGE_SIZE` items were already shown on earlier
        // scroll triggers; the append partial only needs the delta.
        let start = (page as usize).saturating_sub(1) * SEARCH_PAGE_SIZE;
        let new_items = if results.len() > start {
            results.split_off(start)
        } else {
            Vec::new()
        };
        return ResultsAppendPartial {
            query,
            results: new_items,
            next_page,
            musescore_pending: false,
        }
        .into_response();
    }
    // Emit the deferred MuseScore loader only on the first page of a real
    // query when MuseScore is among the selected sources. Page 2+ (infinite
    // scroll) already loaded MuseScore on page 1; appends are handled above.
    let musescore_defer_url = if page == 1 && musescore_selected {
        Some(build_musescore_defer_url(&query, &filters))
    } else {
        None
    };
    render_response(
        is_htmx,
        &state,
        &query,
        results,
        next_page,
        source_filter.as_ref(),
        &filters,
        musescore_defer_url,
    )
}

/// Build the `/search?defer=musescore&…` URL the deferred loader fetches.
/// Carries the query plus the filters MuseScore needs: `instrument` is
/// pushed down to MuseScore's upstream facet, while difficulty / score_type
/// / pd_only are re-applied post-hoc in the defer-mode handler. The
/// `sources` param is intentionally omitted — defer mode forces a
/// MuseScore-only fan-out regardless.
fn build_musescore_defer_url(query: &str, filters: &SearchFilters) -> String {
    let mut url = format!("/search?defer=musescore&q={}", urlencoding::encode(query));
    if let Some(i) = filters.instrument {
        url.push_str("&instrument=");
        url.push_str(i.slug());
    }
    if let Some(d) = filters.difficulty {
        url.push_str("&difficulty=");
        url.push_str(d.slug());
    }
    if let Some(st) = filters.score_type {
        url.push_str("&score_type=");
        url.push_str(st.slug());
    }
    if filters.public_domain_only {
        url.push_str("&pd_only=1");
    }
    url
}

/// Bare append partial with no items + no sentinel. Used for the
/// degenerate empty/short-query case so a sentinel-fired request still
/// gets a clean response shape rather than a render of the full page.
fn empty_append(query: &str) -> Response {
    ResultsAppendPartial {
        query: query.to_string(),
        results: Vec::new(),
        next_page: None,
        musescore_pending: false,
    }
    .into_response()
}

/// HTMX requests get the results-only partial (filter controls live outside
/// the swap target so they don't need re-rendering); full-page navigations
/// render the search shell with filter state populated.
fn render_response(
    is_htmx: bool,
    state: &AppState,
    query: &str,
    results: Vec<SearchResult>,
    next_page: Option<u32>,
    source_filter: Option<&HashSet<String>>,
    filters: &SearchFilters,
    musescore_defer_url: Option<String>,
) -> Response {
    let musescore_pending = musescore_defer_url.is_some();
    if is_htmx {
        ResultsPartial {
            query: query.to_string(),
            results,
            next_page,
            musescore_defer_url,
            musescore_pending,
        }
        .into_response()
    } else {
        let ui = build_filter_options(state, source_filter, filters);
        let selected_source_count = ui.sources.iter().filter(|s| s.selected).count();
        // "Active" = anything diverging from the home-page default (all
        // sources ticked, no dropdown selection, PD-only off). Drives
        // the Reset-filters link visibility.
        let has_active_filters = selected_source_count < ui.sources.len()
            || filters.instrument.is_some()
            || filters.difficulty.is_some()
            || filters.score_type.is_some()
            || filters.public_domain_only;
        SearchPage {
            query: query.to_string(),
            results,
            message: None,
            next_page,
            selected_source_count,
            has_active_filters,
            public_domain_only: filters.public_domain_only,
            sources: ui.sources,
            instruments: ui.instruments,
            difficulties: ui.difficulties,
            score_types: ui.score_types,
            musescore_defer_url,
            musescore_pending,
        }
        .into_response()
    }
}

async fn pdf_handler(
    State(state): State<AppState>,
    headers: HeaderMap,
    Path((source_id, id)): Path<(String, String)>,
) -> Response {
    let ip = audit::client_ip(&headers);
    let ua = audit::user_agent(&headers);

    let source = match state.find_source(&source_id) {
        Some(s) => s,
        None => {
            audit::record(
                &state.pool,
                &ip,
                ua.as_deref(),
                "pdf",
                Some(&format!("{source_id}/{id}")),
                "unknown_source",
                None,
            )
            .await;
            return (axum::http::StatusCode::NOT_FOUND, "Unknown source").into_response();
        }
    };

    match source.fetch_pdf_bytes(&id, MAX_PDF_BYTES).await {
        Ok(bytes) => {
            health::record_ok(&state.source_health, source.id());
            audit::record(
                &state.pool,
                &ip,
                ua.as_deref(),
                "pdf",
                Some(&format!("{source_id}/{id}")),
                "ok",
                Some(&format!(r#"{{"bytes":{}}}"#, bytes.len())),
            )
            .await;
            let mut out = HeaderMap::new();
            out.insert(header::CONTENT_TYPE, HeaderValue::from_static("application/pdf"));
            let fname = sanitize_filename(&id);
            if let Ok(v) = HeaderValue::from_str(&format!(r#"inline; filename="{fname}.pdf""#)) {
                out.insert(header::CONTENT_DISPOSITION, v);
            }
            (out, bytes).into_response()
        }
        Err(e) => {
            tracing::warn!(
                source = %source_id,
                id = %id,
                error = %e,
                "fetch_pdf_bytes failed; falling back to external_url"
            );
            health::record_err(&state.source_health, source.id(), &e.to_string());
            audit::record(
                &state.pool,
                &ip,
                ua.as_deref(),
                "pdf",
                Some(&format!("{source_id}/{id}")),
                "fetch_failed_redirect",
                None,
            )
            .await;
            Redirect::to(&source.external_url(&id)).into_response()
        }
    }
}

fn sanitize_filename(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            'A'..='Z' | 'a'..='z' | '0'..='9' | '.' | '-' | '_' => c,
            _ => '_',
        })
        .collect()
}

async fn login_page() -> impl IntoResponse {
    LoginTemplate { error: None }
}

#[derive(Deserialize)]
struct LoginForm {
    password: String,
}

async fn login_submit(
    State(state): State<AppState>,
    session: Session,
    Form(form): Form<LoginForm>,
) -> impl IntoResponse {
    match auth::verify_admin(&state.pool, &form.password).await {
        Ok(true) => {
            if let Err(e) = session.insert("admin", true).await {
                tracing::warn!(error = %e, "session insert failed");
            }
            Redirect::to("/admin").into_response()
        }
        Ok(false) => LoginTemplate {
            error: Some("Invalid password".into()),
        }
        .into_response(),
        Err(e) => {
            tracing::error!(error = %e, "verify_admin failed");
            LoginTemplate {
                error: Some("Internal error".into()),
            }
            .into_response()
        }
    }
}

async fn logout(session: Session) -> impl IntoResponse {
    let _ = session.flush().await;
    Redirect::to("/login")
}
